### ISSUE TITLE
Is there any easy way to visualize the bounding box?

### ISSUE THREAD

**Issue by facade1801** [appinho/ROS_Perception_Package_Kitti_Dataset#10]
Hello. I am new to this, and I have run all other .launch files given. I have seen the PointClouds successfully, but I cannot generate the bounding box shown in the Readme gif.
Is there any easy way to visualize the bounding box, or am I making a simple mistake? (I think may be it is related to the visualization module?)
Thanks!

**Comment by facade1801** [comment]
**evaluation.launch** seems to be the solution, but it stops running halfway. Trying to debug :-)

**Comment by appinho** [comment]
Does it freeze or crash for you half way @facade1801 ?

Maybe try a slower replay rate like 0.1 to check if it you pc performance.

**Comment by appinho** [comment]
I found a small bug. Make sure to pull first and then let me know if your error is still there ;)

**Comment by facade1801** [comment]
I pulled and run evaluation.launch. This is what I get. (I added some output="screen".)
Do I need to open Rviz in advance?

```facade@facade-VirtualBox:~$ cd catkin_ws/
facade@facade-VirtualBox:~/catkin_ws$ roslaunch evaluation evaluation.launch scenario:=0060
... logging to /home/facade/.ros/log/4bc13a52-f47d-11e8-945d-0800277d5ebd/roslaunch-facade-VirtualBox-2197.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://facade-VirtualBox:41295/

SUMMARY
========

PARAMETERS
 * /detection_node/car/height/max: 2.0
 * /detection_node/car/height/min: 1.1
 * /detection_node/car/semantic/min: 0.6
 * /detection_node/car/side/max: 6.0
 * /detection_node/car/side/min: 1.3
 * /detection_node/grid/cell/height: 0.15
 * /detection_node/grid/cell/size: 0.25
 * /detection_node/grid/range/max: 83.0
 * /detection_node/grid/range/min: 3.0
 * /detection_node/grid/segments: 240
 * /detection_node/lidar/height: -1.73
 * /detection_node/lidar/z_min: -2.4
 * /detection_node/pedestrian/height/max: 2.25
 * /detection_node/pedestrian/height/min: 1.1
 * /detection_node/pedestrian/semantic/min: 0.8
 * /detection_node/pedestrian/side/max: 2.1
 * /detection_node/pedestrian/side/min: 0.55
 * /detection_node/ransac/iterations: 50
 * /detection_node/ransac/tolerance: 0.2
 * /detection_node/semantic/edge_detection/kernel: 3
 * /detection_node/semantic/edge_detection/max: 120
 * /detection_node/semantic/edge_detection/min: 5
 * /detection_node/semantic/edge_detection/perform: False
 * /evaluation_node/scenario: 60
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /sensor_setup_node/grid/cell/height: 0.15
 * /sensor_setup_node/grid/cell/size: 0.25
 * /sensor_setup_node/grid/range/max: 83.0
 * /sensor_setup_node/grid/range/min: 3.0
 * /sensor_setup_node/grid/segments: 240
 * /sensor_setup_node/lidar/height: -1.73
 * /sensor_setup_node/lidar/z_min: -2.4
 * /sensor_setup_node/ransac/iterations: 50
 * /sensor_setup_node/ransac/tolerance: 0.2
 * /sensor_setup_node/scenario: 60
 * /sensor_setup_node/semantic/edge_detection/kernel: 3
 * /sensor_setup_node/semantic/edge_detection/max: 120
 * /sensor_setup_node/semantic/edge_detection/min: 5
 * /sensor_setup_node/semantic/edge_detection/perform: False
 * /tracking_node/data_association/car/dist/form: 5.0
 * /tracking_node/data_association/car/dist/position: 2.0
 * /tracking_node/data_association/ped/dist/form: 2.0
 * /tracking_node/data_association/ped/dist/position: 1.0
 * /tracking_node/track/P_init/v: 10.0
 * /tracking_node/track/P_init/x: 1.0
 * /tracking_node/track/P_init/y: 1.0
 * /tracking_node/track/P_init/yaw: 10.0
 * /tracking_node/track/P_init/yaw_rate: 1.0
 * /tracking_node/tracking/aging/bad: 2
 * /tracking_node/tracking/dim/x: 5
 * /tracking_node/tracking/dim/x_aug: 7
 * /tracking_node/tracking/dim/z: 2
 * /tracking_node/tracking/lambda: 2.0
 * /tracking_node/tracking/occlusion_factor: 2.0
 * /tracking_node/tracking/std/acc: 0.4
 * /tracking_node/tracking/std/lidar/x: 0.15
 * /tracking_node/tracking/std/lidar/y: 0.15
 * /tracking_node/tracking/std/yaw_rate: 0.314
 * /visualization_node/scenario: 60

NODES
  /
    detection_node (detection/detection)
    evaluation_node (evaluation/evaluation)
    sensor_setup_node (sensor_processing/sensor_setup)
    tracking_node (tracking/tracking)
    visualization_node (visualization/visualization)

auto-starting new master
process[master]: started with pid [2208]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4bc13a52-f47d-11e8-945d-0800277d5ebd
process[rosout-1]: started with pid [2221]
started core service [/rosout]
process[sensor_setup_node-2]: started with pid [2232]
process[detection_node-3]: started with pid [2239]
process[tracking_node-4]: started with pid [2240]
[ INFO] [1543567963.110705987]: ped_side_min 0.55
[ INFO] [1543567963.110812841]: ped_side_max 2.1
[ INFO] [1543567963.110853396]: ped_height_min 1.1
[ INFO] [1543567963.110882589]: ped_height_max 2.25
[ INFO] [1543567963.110910106]: ped_semantic_min 0.8
[ INFO] [1543567963.110937946]: car_side_min 1.3
[ INFO] [1543567963.110964853]: car_side_max 6
[ INFO] [1543567963.110990880]: car_height_min 1.1
[ INFO] [1543567963.111017004]: car_height_max 2
[ INFO] [1543567963.111043484]: car_semantic_min 0.6
process[visualization_node-5]: started with pid [2241]
process[evaluation_node-6]: started with pid [2295]
[ INFO] [1543567963.269922291]: Read scenario : 0060 
[ INFO] [1543567963.431987596]: scenario 0060
[ INFO] [1543567963.432162500]: lidar_height -1.73
[ INFO] [1543567963.432212017]: lidar_z_min -2.4
[ INFO] [1543567963.432245326]: grid_range_min 3
[ INFO] [1543567963.432277155]: grid_range_max 83
[ INFO] [1543567963.432306352]: grid_height 332
[ INFO] [1543567963.432333728]: grid_width 664
[ INFO] [1543567963.432362115]: grid_cell_size 0.25
[ INFO] [1543567963.432391680]: grid_cell_height 0.15
[ INFO] [1543567963.432420499]: grid_bins 470
[ INFO] [1543567963.432448269]: grid_segments 240
[ INFO] [1543567963.432478244]: ransac_tolerance 0.2
[ INFO] [1543567963.432514560]: ransac_iterations 50
[ INFO] [1543567963.432545878]: inv_angular_res 152.789
[ INFO] [1543567963.432575479]: inv_radial_res 4
[ INFO] [1543567963.437005778]: da_ped_dist_pos 1
[ INFO] [1543567963.437291259]: da_ped_dist_form 2
[ INFO] [1543567963.437396556]: da_car_dist_pos 2
[ INFO] [1543567963.437493305]: da_car_dist_form 5
[ INFO] [1543567963.437586205]: tra_dim_z 2
[ INFO] [1543567963.437675510]: tra_dim_x 5
[ INFO] [1543567963.437762310]: tra_dim_x_aug 7
[ INFO] [1543567963.437851957]: tra_std_lidar_x 0.15
[ INFO] [1543567963.438312463]: tra_std_lidar_y 0.15
[ INFO] [1543567963.438684051]: tra_std_acc 0.4
[ INFO] [1543567963.438962294]: tra_std_yaw_rate 0.314
[ INFO] [1543567963.439137753]: tra_lambda 2
[ INFO] [1543567963.439306829]: tra_aging_bad 2
[ INFO] [1543567963.439861108]: tra_occ_factor 2
[ INFO] [1543567963.440016741]: p_init_x 1
[ INFO] [1543567963.440209813]: p_init_y 1
[ INFO] [1543567963.440454218]: p_init_v 10
[ INFO] [1543567963.440626267]: p_init_yaw 10
[ INFO] [1543567963.440813338]: p_init_yaw_rate 1

```

**Comment by appinho** [comment]
Yes! Please run rviz in advance! I didn’t include the launch command in the evaluation.launch there. Well spotted!
Let me know if you need help to visualize the boxes. And also let me know if things work just with this fix :)

**Comment by facade1801** [comment]
This is what I did:
terminal 1: roscore
terminal 2: rviz
terminal 3: roslaunch evaluation evaluation.launch scenario:=0060
Nothing happens now. Maybe I should add some display in rviz? but I can only see the pointclouds and original images, but no sem￼antic images and no bounding boxes.
Then I tried terminal 4: rosbag play -l -r 0.1 synchronized_data.bag
And I still see nothing there

![image](https://user-images.githubusercontent.com/25151973/49285186-c5e10200-f4d1-11e8-9ec5-5a12651783fe.png)

**Comment by appinho** [comment]
Thanks @facade1801 for your helpful feedback!

I found one more bug and removed it. So pull first :)

Then run the terminals again as you already described. Good job there! Once you start the rosbag play you can hit the space bar and pause it to include all items you want to visualize. Let me know if this works or not.

If not maybe run the tracking.launch as well and let me know if you get the same behavior! 
Thanks for your help to make my project better :)

**Comment by facade1801** [comment]
I still cannot visualize them, the problem remains the same. Same with tracking.launch.

**Comment by appinho** [comment]
It’s only the boxes that you can’t visualize or even the semantic images for example?

Maybe don’t execute roscore because roslaunch already has a roscore command included.

**Comment by facade1801** [comment]
I can't visualize both the boxes and the semantic images for example.
Maybe it's because I have problem reading semantic images.

No image received in:
/sensor/image/detection_grid
/sensor/image/semantic
/viz/detection/image
/viz/tracking/image

**Comment by appinho** [comment]
Check that you have downloaded the semantic images and stored them in the right folder as described in the read me.

Then run:
Terminal 1: roslaunch sensor_processing sensor.launch scenario:=0060

Terminal 2: rosbag play -r 0.25 synchronized_data.bag

And check if you can see the topic /sensor/image/semantic

**Comment by facade1801** [comment]
I have checked the files, seems no problem.
<img width="551" alt="2018-11-30 9 16 28" src="https://user-images.githubusercontent.com/25151973/49291447-4eb56900-f4e5-11e8-898e-df2f70608e89.png">

Below are the results. I have seen similar problems in another issue, and I also have similar result.
<img width="942" alt="2018-11-30 9 14 44" src="https://user-images.githubusercontent.com/25151973/49291454-5412b380-f4e5-11e8-87f4-64153d4a5dbc.png">
<img width="857" alt="2018-11-30 9 14 38" src="https://user-images.githubusercontent.com/25151973/49291455-5412b380-f4e5-11e8-906c-328612795bbf.png">
<img width="500" alt="2018-11-30 9 12 49" src="https://user-images.githubusercontent.com/25151973/49291456-54ab4a00-f4e5-11e8-9200-695ebb91cf3e.png">

**Comment by appinho** [comment]
Thanks for the images! They help a lot to debug further!

Jump into the file sensor_fusion.cpp line 545 within the sensor_processing_lib and print out the path_name. You can use a ROS_INFO command here and make sure to catkin_make the code after. Then look at the print and let me know what it says.

Side note: The variable time_frame currently overflows when you play the scenario more than once so always kill and set up rviz again before running again.

**Comment by facade1801** [comment]
I forgot to catkin_make before... This really helps!
However, after correcting my mistakes and catkin_make, it resulted in this:

<img width="951" alt="2018-12-01 12 59 38" src="https://user-images.githubusercontent.com/25151973/49303472-baf39500-f504-11e8-92d7-695a580da045.png">
<img width="945" alt="2018-12-01 12 52 05" src="https://user-images.githubusercontent.com/25151973/49303480-bfb84900-f504-11e8-9754-e4d65a4736bc.png">

so everything seems going fine except the semantic images 🤯
the images are "received", but does not show

**Comment by facade1801** [comment]
I tried evaluation.launch and the bounding boxes showed thankfully, so the semantic images are no longer a great problem. Thank you a lot for your timely help! it really helps a lot.
Maybe "~" and "/home/username" are not entirely the same and I have to manually hardcode them, because it gets better after changing them to my own path (with unknown reason.)

<img width="999" alt="2018-12-01 1 40 12" src="https://user-images.githubusercontent.com/25151973/49305582-9ac6d480-f50a-11e8-8422-ac3f4b30a08c.png">

**Comment by appinho** [comment]
Happy that it works now 💯 
Yeah, I guess the path is a ROS issue! I will find a work around within the next weeks! Make sure to Star and follow the repository to be up to date! ;-)

What is your background @facade1801 and what are you currently working on?

**Comment by facade1801** [comment]
I'm struggling with my graduating project of undergraduate, and my project is mainly about point cloud, autopilot and object detection. Thanks for caring 😇

**Comment by appinho** [comment]
Awesome project! 🚀 

Let me know if you need any further help or if you have any ideas, feedback or recommendations about developing my repo in a better way :)

**Comment by 807xuan** [comment]
> I have checked the files, seems no problem. <img alt="2018-11-30 9 16 28" width="551" src="https://user-images.githubusercontent.com/25151973/49291447-4eb56900-f4e5-11e8-898e-df2f70608e89.png">
> 
> Below are the results. I have seen similar problems in another issue, and I also have similar result. <img alt="2018-11-30 9 14 44" width="942" src="https://user-images.githubusercontent.com/25151973/49291454-5412b380-f4e5-11e8-87f4-64153d4a5dbc.png"> <img alt="2018-11-30 9 14 38" width="857" src="https://user-images.githubusercontent.com/25151973/49291455-5412b380-f4e5-11e8-906c-328612795bbf.png"> <img alt="2018-11-30 9 12 49" width="500" src="https://user-images.githubusercontent.com/25151973/49291456-54ab4a00-f4e5-11e8-9200-695ebb91cf3e.png">

Sorry to bother you, can you tell me how to generate a semantically segmented picture under kitti_data/0060/segmented file?

**Comment by 807xuan** [comment]
> I have checked the files, seems no problem. <img alt="2018-11-30 9 16 28" width="551" src="https://user-images.githubusercontent.com/25151973/49291447-4eb56900-f4e5-11e8-898e-df2f70608e89.png">
> 
> Below are the results. I have seen similar problems in another issue, and I also have similar result. <img alt="2018-11-30 9 14 44" width="942" src="https://user-images.githubusercontent.com/25151973/49291454-5412b380-f4e5-11e8-87f4-64153d4a5dbc.png"> <img alt="2018-11-30 9 14 38" width="857" src="https://user-images.githubusercontent.com/25151973/49291455-5412b380-f4e5-11e8-906c-328612795bbf.png"> <img alt="2018-11-30 9 12 49" width="500" src="https://user-images.githubusercontent.com/25151973/49291456-54ab4a00-f4e5-11e8-9200-695ebb91cf3e.png">

**Comment by 807xuan** [comment]
Sorry to bother you, can you tell me how to generate a semantically segmented picture under kitti_data/0060/segmented file?
