### ISSUE TITLE
Segment personal image in ros

### ISSUE THREAD

**Issue by weisongwen** [appinho/ROS_Perception_Package_Kitti_Dataset#12]
Hi @appinho , Thanks for your sharing this great work,
I have a image which contains trees, buildings and sky. How can i use your package to segment my image ?
For example, segment the trees, buildings and sky area
thanks a lot,
Best,
Welson

**Comment by appinho** [comment]
Hi @weisongwen,

your best bet is to use Google's DeepLab if your image has nothing to do with the KITTI Dataset: https://github.com/tensorflow/models/tree/master/research/deeplab

if your image is from the KITTI Dataset you can use the trained KITTIDeepLab:
https://github.com/hiwad-aziz/kitti_deeplab

Let me know if this helps!

**Comment by weisongwen** [comment]
Hi @appinho , Thanks for your kind reply, Actually, i want to have the image segmentation ros available and do not rely on the tensorflow. just like your package.  Moreover, i do not need perfect performance of segmentation, 

in this case, could you please tell me which node do i need to use regarding to your package?

Best,
Welson,

**Comment by appinho** [comment]
Hi @weisongwen,

I precalculate the semantic images with the help of Tensorflow and then just call them within my sensor fusion node in ROS. So, unfortunately, my method relies on Tensorflow to perform image segmentation. Why don't you want to use Tensorflow since it is such a strong AI framework?

**Comment by weisongwen** [comment]
Hi @appinho ,

Thanks for your kind reply. The computation power if my device is limited.  I will go to https://github.com/tensorflow/models/tree/master/research/deeplab next,

Best,
Welson,

**Comment by appinho** [comment]
Hi @weisongwen ,

if your computational power is limited also google for **"Mobile Deep Learning"** since they are designed for mobile devices which have weaker processors but still need to perform in real time. Good luck and let me know if you need further help!
