### ISSUE TITLE
Failed to launch evaluation evaluation.launch

### ISSUE THREAD

**Issue by Sakura1221** [appinho/ROS_Perception_Package_Kitti_Dataset#13]
I have run **roslaunch evaluation evaluation.launch scenario:=0001** and I got a warning like this

[ INFO] [1553662220.801529193]: Read scenario : 0001 
[ WARN] [1553662223.935368898]: Error opening file
[ INFO] [1553662223.935418984]: Publishing Evaluation [0]
[ WARN] [1553662224.441130598]: Error opening file
[ INFO] [1553662224.441191681]: Publishing Evaluation [1]
[ WARN] [1553662224.958780696]: Error opening file

Then, I check the **evaluation.cpp**, I found there is no **kitti_results folder**. Would you please upload it?
Thank you very much!

```
// Delete content in file if there is one
	filename_ = 
		"~/kitti_results/"
		+ scenario_name + ".txt";
	tracking_results_.open(filename_.c_str(),
		std::ofstream::out | std::ofstream::trunc);
```

**Comment by appinho** [comment]
Good catch @Sakura1221 ! Will have a look at it in the next days and make a fixing push!

**Comment by appinho** [comment]
@Sakura1221 it is merged in the master now! Sorry for the long wait! Just apply the ReadMe and you can evaluate the demo now :)
