### ISSUE TITLE
[detection.launch] is neither a launch file in package [detection] nor is [detection] a launch file name  [tracking.launch] is neither a launch file in package [tracking] nor is [tracking] a launch file nam

### ISSUE THREAD

**Issue by ghost** [appinho/ROS_Perception_Package_Kitti_Dataset#15]
Hi,

When i executed
roslaunch detection detection.launch home_dir:=/home/sana
roslaunch tracking tracking.launch home_dir:=/home/sana

i got the error below: Kindly help
[detection.launch] is neither a launch file in package [detection] nor is [detection] a launch file name
The traceback for the exception was written to the log file

[tracking.launch] is neither a launch file in package [tracking] nor is [tracking] a launch file name
The traceback for the exception was written to the log file

**Comment by appinho** [comment]
Hi,

execute:

source devel/setup.bash

in your workspace to link built ros packages and then try again the roslaunch commands.
Best,
Simon
