### ISSUE TITLE
track algorithm

### ISSUE THREAD

**Issue by Renataaa** [appinho/ROS_Perception_Package_Kitti_Dataset#17]
Hi， I want to ask why tracks_[i].x(2) is less than 0 which should be the velocity.

**Comment by appinho** [comment]
Hi @Renataaa ! Thanks for the comment and the observation. This can happen with an UKF and it’s Constant Turn Rate Model. It simply means that the velocity faces in the other direction (180 degree). Can you share which scenario, time step and track id yo observe this and I can have a look at it

**Comment by Renataaa** [comment]
The first timestamp, the object's position is (-5425.71 4597.6) the  second timestamp, the target position is (-5426.88 4605.34) and I match them manually. but the tracker only accquire the velocity of 1.06 which is too slow, i think. I saw in prediction function that there is a opetation delta_t * v , but in update function where the tracker acquire the velocity there is not any parameter corresponding to time. Thanks for reply

**Comment by Renataaa** [comment]
@appinho Hi?

**Comment by appinho** [comment]
Hey,

I’m on vacation this week but I once I got back to my Linux machine I give
you an answer

**Comment by Renataaa** [comment]
Oh..... so sorry to bother you.....Have a nice vacation !!! ^_^

**Comment by appinho** [comment]
Ok, so please answer me these questions so I can help you understand my code:

1. Is it the scenario from the demo?
2. How do you get these numbers (-5425.71 4597.6) for the position? Are these world coordinates?
3. How do you output them? Do you see them in your terminal and are they coming from my printTrack() method?

It is true that on the update function you don't use the time anymore. That is just how the UKF works. You predict your state (with a delta_t) and you have your measurement z, and out of these two states and their uncertainties you calculate the combined belief. So you only encounter the use of time in your prediction step.

**Comment by appinho** [comment]
4. The tracking ID of the track you observe your behavior

**Comment by appinho** [comment]
@Renataaa  any updates?

**Comment by Renataaa** [comment]
1, No, it is not any scenario from the demo
2, world coordinates
3, I just print the tracks_[i].sta.x(0) and (1) to locate the postion
I can not understand what the delta_t in predict fuction means when actually I didn't set the time in udpate fuction. 
4. one question more: my demo is 1hz, is the gap too huge?

**Comment by appinho** [comment]
delta_t comes is the time difference of two consecutive ROS messages and is calculated by subtracting the timestamp t0 from the current timestamp t1. It is close to 100ms/10Hz since this is the rate the sensors from KIT have recorded the data.
Therefore I think your frequency of 1Hz is actually too low.

**Comment by Renataaa** [comment]
But, as the example i showed before, 'The first timestamp, the object's position is (-5425.71 4597.6) the second timestamp, the target position is (-5426.88 4605.34) and I match them manually. but the tracker only accquire the velocity of 1.06 which is too slow' is this normal for 1hz ?

**Comment by appinho** [comment]
You still have to explain to me how you calculate these numbers, please! Otherwise, I can't understand it
