### ISSUE TITLE
where is the 0060.zip

### ISSUE THREAD

**Issue by binjiaqm** [appinho/ROS_Perception_Package_Kitti_Dataset#18]
Where can I download the 0060.zip?  I used 0006.zip but only see radar scans in Rviz without images.

**Comment by appinho** [comment]
https://drive.google.com/drive/u/1/folders/1vHpkoC78fPXT64-VFL1H5Mm1bdukK5Qz

I applied the numerations for the files from http://www.cvlibs.net/datasets/kitti/eval_tracking.php

The scenario you search is now 0012

**Comment by binjiaqm** [comment]
The link provided https://drive.google.com/drive/u/1/folders/1vHpkoC78fPXT64-VFL1H5Mm1bdukK5Qz only includes 13 files. 0060.zip is not one of them.  Do I miss anything here?

**Comment by appinho** [comment]
Yes! Previously called scenario 0060 is now scenario 0012

**Comment by binjiaqm** [comment]
I see. Thanks.

**Comment by appinho** [comment]
No problem. Thanks for pointing out that bug
