### ISSUE TITLE
missing some header files

### ISSUE THREAD

**Issue by nsslab** [appinho/ROS_Perception_Package_Kitti_Dataset#2]
In helper package, it looks like that there are some missing header files like #include "helper/Object.h" and namespace helper itself seem not to exist in the source code.

**Comment by appinho** [comment]
I have a look into this @nsslab. Do you still have this error?

**Comment by appinho** [comment]
@nsslab  I solved the issue! Thanks for pointing this out :)

**Comment by appinho** [comment]
Just pull again and let me know if it works for you as well
