### ISSUE TITLE
What do these metrics ‘MOTAL‘， ’MODA‘ and ‘MODP‘ mean?

### ISSUE THREAD

**Issue by deepmeng** [appinho/ROS_Perception_Package_Kitti_Dataset#21]
I guess 'MODA' means 'multi-object detection accuracy'  and 'MODP' means 'multi-object detection precision' ? What about the 'MOTAL'?

**Comment by appinho** [comment]
The paper you look for that explains it all is:

[1] K. Bernardin, R. Stiefelhagen: Evaluating Multiple Object Tracking Performance: The CLEAR MOT Metrics. JIVP 2008.
