### ISSUE TITLE
Empty semantic point cloud!

### ISSUE THREAD

**Issue by layssi** [appinho/ROS_Perception_Package_Kitti_Dataset#23]
downloaded the data and ran everything exactly the smae and I don't get objects.
I only get "Empty semantic point cloud!"
And I also noticed that the folder 
"/kitti_data/0012/segmented_semantic_images/" is one of the folders that is needed.

DO I need to download and make the Kitti Data manually?

**Comment by Dysonsun** [comment]
I have got this problem, how do you fix it?

**Comment by canihaveaname** [comment]
The drive I provided from readme 0012 is downloaded from goose's address Zip, which only contains 0012 Bag file. After running roslaunch, the following results appear:
[ WARN] [1646748554.890493462]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748554.894613255]: Empty semantic point cloud!
[ WARN] [1646748555.400600677]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748555.404701194]: Empty semantic point cloud!
[ WARN] [1646748555.923053514]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748555.927108425]: Empty semantic point cloud!
[ WARN] [1646748556.439107921]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748556.443300419]: Empty semantic point cloud!
[ WARN] [1646748556.961663497]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748556.965640884]: Empty semantic point cloud!
[ WARN] [1646748557.478409474]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748557.482468366]: Empty semantic point cloud!
[ WARN] [1646748557.997741672]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748558.001720665]: Empty semantic point cloud!
[ WARN] [1646748558.511803933]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748558.515771263]: Empty semantic point cloud!
[ WARN] [1646748559.034038873]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748559.038129333]: Empty semantic point cloud!
[ WARN] [1646748559.544194778]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748559.548134172]: Empty semantic point cloud!

Do you have any other files to download, or do I need to do some other work? Please help me list a detailed reproduction process, the files I need to download and the work I need to complete. I'm just beginning to learn this field. Thank you very much for your help

**Comment by appinho** [comment]
I had some time to fix thie issue. Make sure to pull the newest commit from the master branch
