### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by karanchawla** [appinho/ROS_Perception_Package_Kitti_Dataset#3]
Thanks for the sharing the awesome work, I'd like to replicate this and maybe use this in conjunction with voxelnet. It'll be great if the current README could be updated so that I work with this.

**Comment by appinho** [comment]
Great idea with the Voxelnet!!! Definitely, let me know if you gain any interesting insides with this approach! Really excited to hear back from you regarding this method :+1: 

I just started to add a documentation / work through! You can find it in the ReadMe. Let me also know here if anything is buggy or needs better explanation!

Make also sure to star the repo so you always stay up-to-date :-)
