### ISSUE TITLE
Segmented Images registration

### ISSUE THREAD

**Issue by akash-sachan** [appinho/ROS_Perception_Package_Kitti_Dataset#7]
How do I visualize the scenario as shown in
https://raw.githubusercontent.com/appinho/ROS_Perception_Package_Kitti_Dataset/master/videos/rviz.gif 
That is, segmented images registered on the point cloud ?

**Comment by appinho** [comment]
Please run the tracking.launch and in another terminal run:

rostopic list

And comment the output here.

**Comment by akash-sachan** [comment]
/clicked_point
/clock
/detection/objects
/initialpose
/kitti/camera_color_left/camera_info
/kitti/camera_color_left/image_raw
/kitti/camera_color_right/camera_info
/kitti/camera_color_right/image_raw
/kitti/camera_gray_left/camera_info
/kitti/camera_gray_left/image_raw
/kitti/camera_gray_right/camera_info
/kitti/camera_gray_right/image_raw
/kitti/oxts/gps/fix
/kitti/oxts/gps/vel
/kitti/oxts/imu
/kitti/velo/pointcloud
/move_base_simple/goal
/rosout
/rosout_agg
/sensor/cloud/elevated
/sensor/cloud/filtered
/sensor/cloud/ground
/sensor/cloud/groundplane/inliers
/sensor/cloud/groundplane/outliers
/sensor/cloud/semantic
/sensor/cloud/semantic_sparse
/sensor/grid/occupancy
/sensor/grid/occupancy_updates
/sensor/image/detection_grid
/sensor/image/semantic
/sensor/voxel/elevated
/sensor/voxel/ground
/tf
/tf_static
/tracking/objects
/viz/detection/cubes
/viz/detection/image
/viz/detection/texts
/viz/tracking/arrows
/viz/tracking/arrows_array
/viz/tracking/cubes
/viz/tracking/cubes_array
/viz/tracking/image
/viz/tracking/texts

**Comment by appinho** [comment]
Thanks @spurs-25

So the semantic colored pointcloud2 you should see under the topic:

/sensor/cloud/semantic

The tracking boxes, arrows and IDs under the topics:

/viz/tracking/...

The images on the left hand side, you can visualize with adding:

/sensor/Image/...

Let me know if any of this don’t work or you want me to further explain how to visualize them ;)

**Comment by akash-sachan** [comment]
I ran sensor.launch
Now I'm only visualizing the point clouds with these topics:
  /sensor/cloud/semantic
  /sensor/cloud/semantic_sparse
  /kitti/velo/pointcloud
  /sensor/cloud/ground

This gives the output I wanted except that the semantic segmentation registered on the cloud doesn't seem to move

**Comment by appinho** [comment]
With „doesn’t seemed to move“ you mean one steady colorized point cloud that doesn’t change over time? If not, please explain in detail

**Comment by akash-sachan** [comment]
Yes, 'one steady colorized point cloud that doesn’t change over time'.

Also, for tracking.launch, there's only 1 pointlcoud2 already present (sensor/cloud/semantic_sparse).
And when I add another for (/sensor/cloud/semantic), I can't seem to change its position nor color transformer so it's not showing on the screen

**Comment by appinho** [comment]
If you only visualize the /kitti/velo/pointcloud and the /sensor/image/semantic you see normal moving behavior?

**Comment by appinho** [comment]
Any updates @spurs-25 ?

**Comment by akash-sachan** [comment]
The /sensor/image/semantic doesn't move at all.
In /kitti/velo/pointlcoud, the bikes/cars move as expected

**Comment by appinho** [comment]
I made some changes and explained them in the readme under point 7. It is easier to split up the ROS node from the replaying. Let me know if it works now @spurs-25

**Comment by appinho** [comment]
I guess it is working now since I don't hear back from you @spurs-25 . If the data doesn't move, make sure to close RViz and restart the roslaunch command. You can only play back the scenarios once because of an internal counter that overflows otherwise
